# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.3
# Mod Properties
mod_version=2.6.3
maven_group=semmiedev
archives_base_name=disc_jockey_plus
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_api_version=0.156.0+26.2
cloth_config_version=26.2.155
modmenu_version=20.0.1
org.gradle.java.home=C:\\Program Files\\Java\\jdk-21
org.gradle.jvm.version=21
org.gradle.logging.level=info