# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.3
loader_version=0.19.5
# Mod Properties
mod_version=2.7.8
maven_group=semmiedev
archives_base_name=disc_jockey_plus
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_api_version=0.161.0+26.3
cloth_config_version=26.3.158
modmenu_version=20.0.2
org.gradle.java.home=C:\\Program Files\\Java\\jdk-21
org.gradle.jvm.version=21
org.gradle.logging.level=info